language: php

sudo: false

php:
- 5.4
- 5.5
- 5.6
- hhvm
- 7.0
- 7.1
- 7.2

env:
- WP_VERSION=nightly
- WP_VERSION=latest
- WP_VERSION=4.8.4

matrix:
  allow_failures:
    - env: WP_VERSION=nightly

install:
- composer install
  
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
- vendor/bin/phpunit
